const puzzle = {
  title: "Kampioenen Crypto",
  hint: "Vorm met de 3 gevonden woorden een gepaste zin",

  words: [
    {
      clue: "Trump speelt graag komedie",
      answer: "AMERIKAANSTHEATER",
      solutionIndex: 9,
    },
    {
      clue: "Serie van naakte vrouwen",
      answer: "STRIPREEKS",
      solutionIndex: 4,
    },
    {
      clue: "Romeinse keffer",
      answer: "NERO",
      solutionIndex: 1,
    },
    {
      clue: "Vader moet er dringend op gaan staan (ENG)",
      answer: "PASCALE",
      solutionIndex: 5,
      breakAfter: true,
    },
    {
      clue: "Pesticide",
      answer: "DDT",
      solutionIndex: 1,
    },
    {
      clue: "Erg vriendelijke golven",
      answer: "RADIOHALLO",
      solutionIndex: 4,
    },
    {
      clue: "Nooit iets nieuws",
      answer: "HERHALING",
      solutionIndex: 2,
    },
    {
      clue: '...... "Wilde" niet gaan zitten op dat stoeltje',
      answer: "OSCAR",
      solutionIndex: 1,
    },
    {
      clue: "Viering van het brein",
      answer: "MISVERSTAND",
      solutionIndex: 7,
      breakAfter: true,
    },
    {
      clue: "Muziekgroep die veel plezier heeft",
      answer: "LACHBAND",
      solutionIndex: 4,
    },
    {
      clue: "C-Flat",
      answer: "STUDIOHONDERD",
      solutionIndex: 5,
    },
    {
      clue: "Vrouwelijke schimmels",
      answer: "CHAMPIONETTES",
      solutionIndex: 3,
    },
    {
      clue: "Kat x 2",
      answer: "PUSSYCAT",
      solutionIndex: 6,
    },
    {
      clue: "Straatnaam van het café van de kampioenen",
      answer: "VELDWEG",
      solutionIndex: 4,
    },
    {
      clue: "Kleine deur (ENG)",
      answer: "DOORTJE",
      solutionIndex: 2,
    },
    {
      clue: "Auto vol kerels (ENG)",
      answer: "CARMEN",
      solutionIndex: 2,
    },
    {
      clue: "muzieknoot + reeks",
      answer: "MISERIE",
      solutionIndex: 2,
    },
    {
      clue: "Muziekgroep, wijze, tovenaar",
      answer: "BALTHAZAR",
      solutionIndex: 3,
    },
  ],

  // Intersections: connects letters between different words
  // Format: { word1Index, letter1Pos, word2Index, letter2Pos, group }
  intersections: [
    { word1Index: 7, letter1Pos: 3, word2Index: 0, letter2Pos: 6, group: "A" },
    { word1Index: 7, letter1Pos: 3, word2Index: 3, letter2Pos: 4, group: "A" },
    { word1Index: 7, letter1Pos: 3, word2Index: 5, letter2Pos: 1, group: "A" },
    { word1Index: 7, letter1Pos: 3, word2Index: 17, letter2Pos: 7, group: "A" },
    { word1Index: 7, letter1Pos: 3, word2Index: 11, letter2Pos: 2, group: "A" },
    { word1Index: 7, letter1Pos: 3, word2Index: 9, letter2Pos: 5, group: "A" },
    { word1Index: 7, letter1Pos: 3, word2Index: 17, letter2Pos: 1, group: "A" },
    { word1Index: 0, letter1Pos: 6, word2Index: 3, letter2Pos: 4, group: "A" },
    { word1Index: 0, letter1Pos: 6, word2Index: 5, letter2Pos: 1, group: "A" },
    { word1Index: 0, letter1Pos: 6, word2Index: 17, letter2Pos: 7, group: "A" },
    { word1Index: 0, letter1Pos: 6, word2Index: 11, letter2Pos: 2, group: "A" },
    { word1Index: 0, letter1Pos: 6, word2Index: 9, letter2Pos: 5, group: "A" },
    { word1Index: 0, letter1Pos: 6, word2Index: 17, letter2Pos: 1, group: "A" },
    { word1Index: 3, letter1Pos: 4, word2Index: 5, letter2Pos: 1, group: "A" },
    { word1Index: 3, letter1Pos: 4, word2Index: 17, letter2Pos: 7, group: "A" },
    { word1Index: 3, letter1Pos: 4, word2Index: 11, letter2Pos: 2, group: "A" },
    { word1Index: 3, letter1Pos: 4, word2Index: 9, letter2Pos: 5, group: "A" },
    { word1Index: 3, letter1Pos: 4, word2Index: 17, letter2Pos: 1, group: "A" },
    { word1Index: 5, letter1Pos: 1, word2Index: 17, letter2Pos: 7, group: "A" },
    { word1Index: 5, letter1Pos: 1, word2Index: 11, letter2Pos: 2, group: "A" },
    { word1Index: 5, letter1Pos: 1, word2Index: 9, letter2Pos: 5, group: "A" },
    { word1Index: 5, letter1Pos: 1, word2Index: 17, letter2Pos: 1, group: "A" },
    {
      word1Index: 17,
      letter1Pos: 7,
      word2Index: 11,
      letter2Pos: 2,
      group: "A",
    },
    { word1Index: 17, letter1Pos: 7, word2Index: 9, letter2Pos: 5, group: "A" },
    {
      word1Index: 17,
      letter1Pos: 7,
      word2Index: 17,
      letter2Pos: 1,
      group: "A",
    },
    { word1Index: 11, letter1Pos: 2, word2Index: 9, letter2Pos: 5, group: "A" },
    {
      word1Index: 11,
      letter1Pos: 2,
      word2Index: 17,
      letter2Pos: 1,
      group: "A",
    },
    { word1Index: 9, letter1Pos: 5, word2Index: 17, letter2Pos: 1, group: "A" },
    { word1Index: 0, letter1Pos: 3, word2Index: 1, letter2Pos: 5, group: "B" },
    { word1Index: 0, letter1Pos: 3, word2Index: 5, letter2Pos: 0, group: "B" },
    { word1Index: 0, letter1Pos: 3, word2Index: 17, letter2Pos: 8, group: "B" },
    {
      word1Index: 0,
      letter1Pos: 3,
      word2Index: 10,
      letter2Pos: 11,
      group: "B",
    },
    { word1Index: 1, letter1Pos: 5, word2Index: 5, letter2Pos: 0, group: "B" },
    { word1Index: 1, letter1Pos: 5, word2Index: 17, letter2Pos: 8, group: "B" },
    {
      word1Index: 1,
      letter1Pos: 5,
      word2Index: 10,
      letter2Pos: 11,
      group: "B",
    },
    { word1Index: 5, letter1Pos: 0, word2Index: 17, letter2Pos: 8, group: "B" },
    {
      word1Index: 5,
      letter1Pos: 0,
      word2Index: 10,
      letter2Pos: 11,
      group: "B",
    },
    {
      word1Index: 17,
      letter1Pos: 8,
      word2Index: 10,
      letter2Pos: 11,
      group: "B",
    },
    { word1Index: 1, letter1Pos: 7, word2Index: 6, letter2Pos: 1, group: "C" },
    { word1Index: 1, letter1Pos: 7, word2Index: 8, letter2Pos: 4, group: "C" },
    { word1Index: 1, letter1Pos: 7, word2Index: 11, letter2Pos: 8, group: "C" },
    { word1Index: 1, letter1Pos: 7, word2Index: 13, letter2Pos: 5, group: "C" },
    { word1Index: 1, letter1Pos: 7, word2Index: 16, letter2Pos: 6, group: "C" },
    { word1Index: 6, letter1Pos: 1, word2Index: 8, letter2Pos: 4, group: "C" },
    { word1Index: 6, letter1Pos: 1, word2Index: 11, letter2Pos: 8, group: "C" },
    { word1Index: 6, letter1Pos: 1, word2Index: 13, letter2Pos: 5, group: "C" },
    { word1Index: 6, letter1Pos: 1, word2Index: 16, letter2Pos: 6, group: "C" },
    { word1Index: 8, letter1Pos: 4, word2Index: 11, letter2Pos: 8, group: "C" },
    { word1Index: 8, letter1Pos: 4, word2Index: 13, letter2Pos: 5, group: "C" },
    { word1Index: 8, letter1Pos: 4, word2Index: 16, letter2Pos: 6, group: "C" },
    {
      word1Index: 11,
      letter1Pos: 8,
      word2Index: 13,
      letter2Pos: 5,
      group: "C",
    },
    {
      word1Index: 11,
      letter1Pos: 8,
      word2Index: 16,
      letter2Pos: 6,
      group: "C",
    },
    {
      word1Index: 13,
      letter1Pos: 5,
      word2Index: 16,
      letter2Pos: 6,
      group: "C",
    },
    { word1Index: 0, letter1Pos: 8, word2Index: 15, letter2Pos: 5, group: "D" },
    { word1Index: 0, letter1Pos: 8, word2Index: 11, letter2Pos: 7, group: "D" },
    { word1Index: 0, letter1Pos: 8, word2Index: 10, letter2Pos: 8, group: "D" },
    { word1Index: 0, letter1Pos: 8, word2Index: 8, letter2Pos: 9, group: "D" },
    { word1Index: 0, letter1Pos: 8, word2Index: 9, letter2Pos: 6, group: "D" },
    { word1Index: 0, letter1Pos: 8, word2Index: 6, letter2Pos: 7, group: "D" },
    {
      word1Index: 15,
      letter1Pos: 5,
      word2Index: 11,
      letter2Pos: 7,
      group: "D",
    },
    {
      word1Index: 15,
      letter1Pos: 5,
      word2Index: 10,
      letter2Pos: 8,
      group: "D",
    },
    { word1Index: 15, letter1Pos: 5, word2Index: 8, letter2Pos: 9, group: "D" },
    { word1Index: 15, letter1Pos: 5, word2Index: 9, letter2Pos: 6, group: "D" },
    { word1Index: 15, letter1Pos: 5, word2Index: 6, letter2Pos: 7, group: "D" },
    {
      word1Index: 11,
      letter1Pos: 7,
      word2Index: 10,
      letter2Pos: 8,
      group: "D",
    },
    { word1Index: 11, letter1Pos: 7, word2Index: 8, letter2Pos: 9, group: "D" },
    { word1Index: 11, letter1Pos: 7, word2Index: 9, letter2Pos: 6, group: "D" },
    { word1Index: 11, letter1Pos: 7, word2Index: 6, letter2Pos: 7, group: "D" },
    { word1Index: 10, letter1Pos: 8, word2Index: 8, letter2Pos: 9, group: "D" },
    { word1Index: 10, letter1Pos: 8, word2Index: 9, letter2Pos: 6, group: "D" },
    { word1Index: 10, letter1Pos: 8, word2Index: 6, letter2Pos: 7, group: "D" },
    { word1Index: 8, letter1Pos: 9, word2Index: 9, letter2Pos: 6, group: "D" },
    { word1Index: 8, letter1Pos: 9, word2Index: 6, letter2Pos: 7, group: "D" },
    { word1Index: 9, letter1Pos: 6, word2Index: 6, letter2Pos: 7, group: "D" },
    { word1Index: 1, letter1Pos: 9, word2Index: 1, letter2Pos: 0, group: "E" },
    { word1Index: 1, letter1Pos: 9, word2Index: 10, letter2Pos: 0, group: "E" },
    {
      word1Index: 1,
      letter1Pos: 9,
      word2Index: 11,
      letter2Pos: 12,
      group: "E",
    },
    { word1Index: 1, letter1Pos: 9, word2Index: 12, letter2Pos: 3, group: "E" },
    { word1Index: 1, letter1Pos: 0, word2Index: 10, letter2Pos: 0, group: "E" },
    {
      word1Index: 1,
      letter1Pos: 0,
      word2Index: 11,
      letter2Pos: 12,
      group: "E",
    },
    { word1Index: 1, letter1Pos: 0, word2Index: 12, letter2Pos: 3, group: "E" },
    {
      word1Index: 10,
      letter1Pos: 0,
      word2Index: 11,
      letter2Pos: 12,
      group: "E",
    },
    {
      word1Index: 10,
      letter1Pos: 0,
      word2Index: 12,
      letter2Pos: 3,
      group: "E",
    },
    {
      word1Index: 11,
      letter1Pos: 12,
      word2Index: 12,
      letter2Pos: 3,
      group: "E",
    },
    { word1Index: 16, letter1Pos: 0, word2Index: 8, letter2Pos: 0, group: "F" },
    { word1Index: 16, letter1Pos: 0, word2Index: 0, letter2Pos: 1, group: "F" },
    { word1Index: 8, letter1Pos: 0, word2Index: 0, letter2Pos: 1, group: "F" },
    { word1Index: 2, letter1Pos: 3, word2Index: 5, letter2Pos: 9, group: "G" },
    { word1Index: 2, letter1Pos: 3, word2Index: 7, letter2Pos: 0, group: "G" },
    { word1Index: 2, letter1Pos: 3, word2Index: 14, letter2Pos: 1, group: "G" },
    { word1Index: 5, letter1Pos: 9, word2Index: 7, letter2Pos: 0, group: "G" },
    { word1Index: 5, letter1Pos: 9, word2Index: 14, letter2Pos: 1, group: "G" },
    { word1Index: 7, letter1Pos: 0, word2Index: 14, letter2Pos: 1, group: "G" },
    {
      word1Index: 10,
      letter1Pos: 12,
      word2Index: 13,
      letter2Pos: 3,
      group: "H",
    },
    {
      word1Index: 10,
      letter1Pos: 12,
      word2Index: 8,
      letter2Pos: 10,
      group: "H",
    },
    {
      word1Index: 10,
      letter1Pos: 12,
      word2Index: 9,
      letter2Pos: 7,
      group: "H",
    },
    {
      word1Index: 10,
      letter1Pos: 12,
      word2Index: 4,
      letter2Pos: 0,
      group: "H",
    },
    {
      word1Index: 13,
      letter1Pos: 3,
      word2Index: 8,
      letter2Pos: 10,
      group: "H",
    },
    { word1Index: 13, letter1Pos: 3, word2Index: 9, letter2Pos: 7, group: "H" },
    { word1Index: 13, letter1Pos: 3, word2Index: 4, letter2Pos: 0, group: "H" },
    { word1Index: 8, letter1Pos: 10, word2Index: 9, letter2Pos: 7, group: "H" },
    { word1Index: 8, letter1Pos: 10, word2Index: 4, letter2Pos: 0, group: "H" },
    { word1Index: 9, letter1Pos: 7, word2Index: 4, letter2Pos: 0, group: "H" },
  ],
};
